apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
    project: "k8s"
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:  
      labels:
        app: "goserver"
        project: "k8s"
    spec:
      containers:
        - name: goserver
          image: "carlosdiegodev/hello-go:v6"
          envFrom:
            - configMapRef:
                name: goserver-env
          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: NAME
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          

